### ISSUE TITLE
htmltest continue-on-error

### ISSUE THREAD

**Issue by jesse-wei** [robb-romans/robb-sh-hugo#86]
I found your blog post [Check links in Hugo with htmltest](https://robb.sh/posts/check-links-in-hugo-with-htmltest/) useful.

Regarding [run-htmltest.yml](https://github.com/robb-romans/robb-sh-hugo/blob/main/.github/workflows/run-htmltest.yml), line 37 `continue-on-error: true` causes the action to display a green checkmark even when a link fails, which is a false negative.

Personally, I prefer the action to provide me a red X to notify me if a link is broken, even though this often causes false positives if a website goes down temporarily, etc.

This can be done by using `if: always()` instead of `continue-on-error: true`.

```yml
      - name: Test HTML
        # continue-on-error: true
        uses: wjdp/htmltest-action@master
        with:
          # For consistency, use the same config file as for local builds
          config: .htmltest.yml
      - name: Archive htmltest results
        # MODIFICATION
        # If Test HTML fails, log results and display a red X
        # Use if: always() instead of continue-on-error: true
        # Source: https://stackoverflow.com/questions/62045967/github-actions-is-there-a-way-to-continue-on-error-while-still-getting-correct
        if: always()
        uses: actions/upload-artifact@v3
```

[Here](https://github.com/jesse-wei/jessewei.dev/blob/main/.github/workflows/htmltest.yml) is `htmltest.yml` from my site's repo.
